### ISSUE TITLE
Api

### ISSUE THREAD

**Issue by las1231** [dznet/proxybet-bot#2]
Откуда мжно взять Api

**Comment by dznet** [comment]
Уточните пожалуйста вопрос.

**Comment by las1231** [comment]
Откуда можно взять апи букмекера для работы скрипта???

сб, 9 мар. 2019 г., 22:55 dzNET <notifications@github.com>:

**Comment by dznet** [comment]
spam has been detected.

**Comment by dznet** [comment]
spam has been detected.
